export default [
  { name: "ANDHRA PRADESH", value: "ANDHRA PRADESH" },
  { name: "ARUNACHAL PRADESH", value: "ARUNACHAL PRADESH" },
  { name: "ASSAM", value: "ASSAM" },
  { name: "BIHAR", value: "BIHAR" },
  { name: "CHHATTISGARH", value: "CHHATTISGARH" },
  { name: "DAMAN & DIU", value: "DAMAN & DIU" },
  { name: "DELHI", value: "DELHI" },
  { name: "GOA", value: "GOA" },
  { name: "GUJARAT", value: "GUJARAT" },
  { name: "HARYANA", value: "HARYANA" },
  { name: "HIMACHAL PRADESH", value: "HIMACHAL PRADESH" },
  { name: "JAMMU & KASHMIR", value: "JAMMU & KASHMIR" },
  { name: "JHARKHAND", value: "JHARKHAND" },
  { name: "KARNATAKA", value: "KARNATAKA" },
  { name: "KERALA", value: "KERALA" },
  { name: "MADHYA PRADESH", value: "MADHYA PRADESH" },
  { name: "MAHARASHTRA", value: "MAHARASHTRA" },
  { name: "MEGHALAYA", value: "MEGHALAYA" },
  { name: "MIZORAM", value: "MIZORAM" },
  { name: "NAGALAND", value: "NAGALAND" },
  { name: "ODISHA", value: "ODISHA" },
  { name: "PUNJAB", value: "PUNJAB" },
  { name: "RAJASTHAN", value: "RAJASTHAN" },
  { name: "SIKKIM", value: "SIKKIM" },
  { name: "TAMIL NADU", value: "TAMIL NADU" },
  { name: "TELANGANA", value: "TELANGANA" },
  { name: "TRIPURA", value: "TRIPURA" },
  { name: "UTTAR PRADESH", value: "UTTAR PRADESH" },
  { name: "UTTARAKHAND", value: "UTTARAKHAND" },
  { name: "WEST BENGAL", value: "WEST BENGAL" },
];
